name: Merge Playlists

on:
  schedule:
    # 每天UTC时间凌晨2点运行（北京时间上午10点）
    - cron: '0 2 * * *'
  workflow_dispatch:  # 允许手动触发
  push:
    branches: [ main ]

jobs:
  merge-playlists:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        
    - name: Run merge script
      run: |
        python merge_playlists.py
        
    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add merged_channels.txt
        git diff --staged --quiet || git commit -m "Auto-update merged channels - $(date +'%Y-%m-%d %H:%M:%S')"
        git push
